spring.application.name=emart



# 포트 설정 (애플리케이션 실행 포트)
server.port=8088

# 세션 정보 유지 방법 설정
server.servlet.session.tracking-modes=cookie

# DB 설정 (이미지 설정값에 맞춤)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# 포트를 3306에서 3309로 수정했습니다.
# 변경할 설정 (수정 후)
spring.datasource.url=jdbc:mariadb://localhost:3309/emart

spring.datasource.username=emart
spring.datasource.password=1234

# MyBatis 설정
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.com.ex.emart.mapper=TRACE

# =======================
# ✅ JWT 설정 (여기부터 추가) # 1시간->30분 유효성 토큰발급시간 
# =======================
jwt.secret=c2lsdmVyYmluZS10ZWNoLXNwcmluZy1kb21haW4tYWJjZGVmZ2gta2V5LXVzZXItc2VjcmV0LWtleS1wYXNzd29yZC0xMjM0NTY=
# 30분
jwt.token-validity-in-seconds=1800 
# 12시간
jwt.refresh-token-validity-in-seconds=43200 


